.config/nushell/login.nu
This PR adds the default [login.nu](https://github.com/nushell/nushell/blob/main/crates/nu-utils/src/sample_config/sample_login.nu) config file from the `nushell` source repo in `~/.config/nushell/login.nu`.
=> add the base config for nushell as a login shell

.config/nushell/scripts/functions.nu
This PR adds the `yt-dl-names` function to `nushell`.
This function allows the user, by giving either a playlist `--id` or a `--channel` id, to download the list of videos inside a playlist or all the playlists of a channel with the `--all` flag.
=> NUSHELL: add a script to download youtube videos metadata

.config/nushell/lib/core/keybindings.nu
This PR simplifies the `nushell` bindings, making them easier to read and better, e.g. `repo goto` won't show on the terminal and won't be part of the history of commands when pressing `C-g`, which is cool :+1:
=> REFACTOR: simplify the custom bindings of `nushell`

.config/nushell/lib/core/hooks.nu, .config/nushell/lib/personal/aliases.nu
This PR adds `ls | ... | grid -c` as an alias as `lsg` and triggers it when changing directory to have an overview of the new `pwd`.
=> FEATURE: add `ls | grid` as alias and hook to `nushell`

.config/nushell/env.nu
This PR uses `vivid` to set the `LS_COLORS` in `nushell`, changing the theme with only `LS_THEME` in `env.nu`.
=> FEATURE: use `vivid` to set the colors of `ls` in `nushell`.

.config/nushell/env.nu
This PR adds the `~/downloads/` directory to the `$env` of `nushell`.
=> FEATURE: add the downloads directory to the environment of `nushell`.

.config/nushell/lib/applications/venv.nu, .config/nushell/lib/applications/vm.nu
This PR uses the better `path exists` command in the scripts, instead of `do -i { ... } | complete | get exit_code`.
=> FIX: use `... | path exists` in `nushell` to test files and directories.

.config/nushell/config.nu, .config/nushell/lib/core/hooks.nu
This PR moves the aliases to the top of the `config.nu` imports, making the aliases available to all the config, e.g. `lsg` in the hooks` :yum:
=> FEATURE: make the aliases available to all the `nushell` config

.config/nushell/config.nu, .config/nushell/env.nu
This PR
- adds a script, `config update default` to the `env.nu` config file to pull the [default config](https://raw.githubusercontent.com/nushell/nushell/main/crates/nu-utils/src/sample_config/default_config.nu) of `nushell` and put it inside the `NU_LIB_DIRS.0` directory
- source this file in `config.nu`
- overwrite custom values with `merge`
=> FEATURE: pull, source and overwrite the default config of `nushell` with custom values

.config/nushell/config.nu, .config/nushell/env.nu, .config/nushell/lib/applications/dotfiles.nu, .config/nushell/lib/applications/prompt.nu, .config/nushell/lib/applications/repo.nu, .config/nushell/lib/applications/venv.nu, .config/nushell/lib/applications/vm.nu, .config/nushell/lib/core/keybindings.nu, .config/nushell/lib/personal/aliases.nu, .config/nushell/lib/scripts/community.nu
This PR:
- activates the trash
- use `--trash` on all the `rm`s in the scripts
- use the `|` pipe symbol at the beginning of the lines in the `PATH` declaration
- add `TOMB_HOME` to the environment
- add previews to `fzf` directly for `repo goto` and `dotfiles edit`, instead of showing them afterwards
- add `--clear` to `repo goto`
- make `C-l` clear the terminal and run `lsg` to show the content of the directory
- add some cross-platform functions from the discord server
=> FEATURE: add miscellaneous updates to `nushell`

.config/qutebrowser/quickmarks
This PR adds some new quickmarks and renames the "oberonproject" quickmarks into the new "oberonforall".
=> UPDATE: add and update quickmarks to `qutebrowser`

.config/gdb/gdbinit
This PR adds a basic config for `gdb`, i.e. not pulling the debuginfo.
=> NEW: add config for `gdb`

.system/etc/pacman.conf
This PR simply removes the broken `dtos-core-repo` library from `pacman`.
=> FIX: remove `dtos-core-repo` from pacman, it's broken

.config/nushell/config.nu, .config/nushell/env.nu, .config/nushell/lib/personal/aliases.nu
Related to https://github.com/goatfiles/nu_scripts/pull/8.
This PR:
- removes the hardcoded prompt functions from `env.nu`, thanks to https://github.com/goatfiles/nu_scripts/pull/8.
- makes `env.nu` a bit easier to read with newlines
- makes the "multiline prompt" prettier with colors
- uses `GIT_REPOS_DIR` to abstract away from `GHQ_ROOT`
- does not force `--trash` on `rm` to allow to delete things `--permanent`ly
=> FEATURE: move `nushell` scripts and refactor `env.nu`

.bashrc, .config/nushell/env.nu
This PR
- fixes the name of the `VISUAL` environment variable in both `nushell` and `bash`
- sets `VISUAL` to the `EDITOR`
now, one only needs to change `export EDITOR=...` in the `bashrc` and `let-env EDITOR = ...` in `config.nu` to change the editor system wise :+1:
=> FIX: use `VISUAL=EDITOR` and not `VISAL=...` in the shells

.bashrc, .config/nushell/env.nu, .config/nvim/init.lua, .config/nvim/lua/user/options.lua, .config/nvim/lua/user/plugins.lua, .gitignore
This PR
- adds a basic config for _Neovim_ thanks to _kickstart.nvim_
- uses `tokyonight` as the colorscheme
- changes the default `EDITOR` to `nvim`
- removes the `VIMINIT` environment variable that breaks the `~/.config/nvim/init.lua` config
- ignore the `packer` compilation `lua` file
> see [`nvim-lua/kickstart.nvim`](https://github.com/nvim-lua/kickstart.nvim) and [:film_projector: _Effective Neovim: Instant IDE_](https://www.youtube.com/watch?v=stqUbv-5u2s)
=> FEATURE: add base *kickstart* config for `nvim`

.config/spicy/settings, .gitignore
This PR
- adds a basic config for `spice`, used to run VM with `qemu`
- this gave me the idea to not avoid all the untracked files, but rather to select which one are to be ignored or not
This PR should allow the `git status` to stay clean but a the same time to see new config files!
=> FEATURE: add a config `gitignore` and `spicy` config

.config/git/config, .config/qutebrowser/quickmarks
In order to sign and verify commits and tags, this PR
- adds my real email address to email-verify commits
- adds my `gpg` public key to both the `git` config and my _GitHub_ account
- makes commits and tags `--signed` by default
- does NOT make pushes `--signed` by default as _GitHub_ does not support them for now
> this causes the following "fatal" error
> ```bash
> > git push --signed
> fatal: the receiving end does not support --signed push
> ```
- adds a `qutebrowser` quickmark to the _GitHub_ documentation about signing and verifying commits
:warning: this PR adds hardcoded personal values, i.e. `email = stevan.antoine@gmail.com` and `signingkey = 7C5EE50BA27B86B7F9D5A7BA37AAE9B486CFF1AB`...
this has been discussed a bit in https://github.com/goatfiles/dotfiles/discussions/20 and …
=> FEATURE: add `gpg` signature support to `git`

install.sh
Related to https://github.com/goatfiles/pkgbuilds/pull/25.
This PR should close #33.
I simply renamed the packages in the `install.sh` script according to the new names over in the `pkgbuilds` :+1:
=> fix the name of the packages from pkgbuilds#25

.config/nushell/lib/core/keybindings.nu
I use macOS and installed nushell via brew. It installs configs in a path that contains a space (blurgh), so when I tried your `reload_config` keybinding as is, it fails. Per the [discussion on discord](https://discord.com/channels/601130461678272522/1093381138434764861/1093381138434764861), I tested surrounding the paths being fed to the source commands with "", then '', and while either of those work on a mac, someone mentioned that only '' works on Windows, so I added '' around the path expansions to handle the case where those paths might contain a space.
=> Quote source paths in reload_config keybinding
